// Code generated by "stringer -type=ProcessState"; DO NOT EDIT.

package enums_eg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Idle-0]
	_ = x[Running-1]
	_ = x[Halted-2]
	_ = x[Stopped-3]
	_ = x[Killed-4]
}

const _ProcessState_name = "IdleRunningHaltedStoppedKilled"

var _ProcessState_index = [...]uint8{0, 4, 11, 17, 24, 30}

func (i ProcessState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ProcessState_index)-1 {
		return "ProcessState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProcessState_name[_ProcessState_index[idx]:_ProcessState_index[idx+1]]
}
